return {
  {
    "williamboman/mason.nvim",
    dependency = {
      "williamboman/mason-lspconfig.nvim",
    },
    opts = {
      ensure_installed = {
        "stylua",
        "shellcheck",
        "shfmt",
        "flake8",
        "black",
        "mypy",
        "ruff",
        "pyright",
        "tailwindcss-language-server",
        "typescript-language-server",
        "js-debug-adapter",
        "css-lsp",
        "html-lsp",
        "intelephense",
        "emmet-language-server",
        "prettier",
        "eslint-lsp",
        "eslint_d",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "yaml-language-server",
        "markdownlint",
        "marksman",
        "markdown-toc",
        "lemminx",
        "xmlformatter",
        "fixjson",
      },
    },
  },
}
